# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:      pretty
baseurl: 	    	/2022sp-UVA-CS-MachineLearningDeep/
url:            https://qiyanjun.github.io/

# Setup
title:            	"2022 Spring UVA CS - Machine Learning"
tagline:          	"2022 Spring"
description:        "TuTh 2pm-3:15PM"
future: 			true

author:
  name:           'Yanjun Qi'
  url:            https://twitter.com/Qdatalab


collections:
  contents:
    sort_by: LOrder
    output: true
